### ISSUE TITLE
Simple CRUD Table /w Codeigniter 4

### ISSUE THREAD

**Issue by m10119002** [m10119002/SIM-PaudMentari#8]
CRUD
C reate = menambah data
R ead = melihat data
U pdate = merubah data
D elete = menghapus data

Database: MariaDB (Xampp)
Framework: Codeigniter 4.1.1

**Comment by m10119002** [comment]
@ginanjartg @agdd1709 monggo ditarik foldernya ke PC masing2, tampilan HTMLnya udah beres?

Github Desktop: https://desktop.github.com/

1. Install Github Desktop
2. Login ke Github Desktop
3. Clone Repository dari projek /m10119002/SIM-PaudMentari
4. Pastikan lokasi folder clone "xampp/htdocs/SIM-PaudMentari"
(*) Jika sudah ada folder "SIM-PaudMentari", ganti dulu nama folder lama jadi "_SIM-PaudMentari" biar bisa clone

Susunan folder samples:
xampp/htdocs/SIM-PaudMentari/samples/..
xampp/htdocs/SIM-PaudMentari/samples/SimpleCRUDTable411/..
xampp/htdocs/SIM-PaudMentari/samples/<nama folder projek>/<isi projeknya>

contoh:
SIM-PaudMentari/samples/HalamanLogin/login.php
SIM-PaudMentari/samples/Dashboard/dashboard.php

**Comment by ginanjar10119032** [comment]
folder HalamanLogin taro di /samples/ aja kan ya? 
bukan di /samples/SimpleCRUDTable411?

**Comment by m10119002** [comment]
> 
> 
> folder HalamanLogin taro di /samples/ aja kan ya?
> bukan di /samples/SimpleCRUDTable411?

ya, buat folder baru aja.. nanti di cek disini
